[package]
name = "display-tasks-on-epaper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.7.1"
embedded-hal = "0.2.7"
epd-waveshare = "0.5.0"
linux-embedded-hal = "0.3.2"

